name: Python Uppercase

on:
  push: 
    paths:
      - ".github/workflows/python-app.yml"
      - "py-upper/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
        run: python -V

      - name: Display current directory
        run: pwd 

      - name: List files
        run: ls -R   

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Check python version
        run: python -V          

    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r py-upper/requirements.txt

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "py-upper/requirements.txt"
          update-pip: "true"

      - name: Run tests
        working-directory: py-upper
        run: pytest -v          


  build:
    runs-on: windows-latest
    needs: test
    strategy:
      matrix:
        python-version: ['3.13', '3.12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "py-upper/requirements.txt"
          update-pip: "true"

      - name: Build project
        run: pyinstaller --onefile py-upper/uppercase.py

      - name: List build output
        run: ls -R dist/

      - name: Rename the exe file
        run: mv dist/uppercase.exe dist/uppercase-${{ matrix.python-version }}.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: uppercase-${{ matrix.python-version }}
          path: dist/uppercase-${{ matrix.python-version }}.exe 
          

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: dist/**
      #     body: "Binaries of the uppercase program"
      #     tag_name: ${{ github.ref_name }}
